site_name: jayi0908's slides
site_url: https://jayi0908.github.io/md-slides/
repo_name: md-slides
repo_url: https://github.com/jayi0908/md-slides
copyright: Copyright &copy; 2025-? <a href="https://github.com/jayi0908" target="_blank" rel="noopener">jayi0908</a>

nav:
  - 首页: index.md

theme:
  name: 'material'
  language: 'zh'
  favicon: assets/icons/favicon.png
  icon: 
    logo: material/notebook-outline
    top: material/arrow-up-thin
  features:
    - navigation.indexes
    - navigation.top # 允许返回顶部
    - navigation.footer # 允许页脚导航
    - navigation.prune # 侧边栏自动折叠
    - navigation.tracking # 在url中使用标题定位锚点
  palette:
    - scheme: slate
      primary: gray
  
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true # 允许使用通用的数学公式
  - attr_list
  - md_in_html

extra:
  generator: true
  social:
    - icon: material/github
      link: https://www.github.com/jayi0908
extra_css:
  - assets/css/stylesheet.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/gh/kjartanhr/JetBrainsMono-Webfont@main/JetBrainsMono/JetBrainsMono.css